services:
  - type: web
    name: todolist
    env: python
    rootDir: py_175
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
